version: 2
jobs:
  working_directory: ~/search-widget-react-redux
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run: |
        npm install -g yarn
        yarn install

      - run: yarn lint
      - run: yarn test
      - run: yarn outdated
