const accounts = [
  "Else Mulcahy",
  "Marth Strouse",
  "Marcie Reynaga",
  "Rowena Galang",
  "Maisha Fulp",
  "Cathie Sanmiguel",
  "Roxie Beckler",
  "Lucille Magnani",
  "Marleen Towry",
  "Chanelle Boshart",
  "Polly Schleifer",
  "Richie Fetters",
  "Jennette Byford",
  "Bettyann Melnyk",
  "Sherri Bobo",
  "Cleopatra Lazard",
  "Lori Chausse",
  "Carie Artz",
  "Alana Valliere",
  "Silvia Batchelder",
];

const transactions = [
  "Chasity Sprenger",
  "Michaele Carbaugh",
  "Heather Scrivner",
  "Julissa Primavera",
  "Anglea Mcjunkin",
  "Carl Mucha",
  "Dovie Sidney",
  "Lee Masser",
  "Ollie Ector",
  "Onie Yoshimoto",
  "Cornelia Curro",
  "Kristle Hruska",
  "Veronique Dimery",
  "Shelba Tagg",
  "Brandy Selig",
  "Rolland Burfield",
  "Hertha Higham",
  "Jae Tran",
  "Nella Sabatino",
  "Leona Laguardia",
];

const other = [
  "Jacqualine Cosey",
  "Lillian Hawes",
  "Marsha Shehorn",
  "Waltraud Boatright",
  "Kit Childers",
  "Dann Kaminski",
  "Selma Bohnert",
  "Tessie Struck",
  "Mandi Parry",
  "Bruna Reynaga",
  "Vilma Allinder",
  "Sacha Freeborn",
  "Lesa Belote",
  "Herman Trout",
  "Shani Schildgen",
  "Janel Bert",
  "Christen Buckler",
  "Stefania Pinkard",
  "Tiffiny Clayson",
  "Patsy Chalmers",
];

export default {
  accounts,
  transactions,
  other,
};
